# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.CharField(max_length=50)),
                ('speaking', models.CharField(max_length=50)),
                ('listening', models.CharField(max_length=50)),
                ('reading', models.CharField(max_length=50)),
                ('writing', models.CharField(max_length=50)),
                ('grammar', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
                ('exams', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.CharField(max_length=50)),
                ('speaking', models.CharField(max_length=50)),
                ('listening', models.CharField(max_length=50)),
                ('reading', models.CharField(max_length=50)),
                ('writing', models.CharField(max_length=50)),
                ('grammar', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
                ('exams', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
